### ISSUE TITLE
Add a command to retrieve data stored by send-blob

### ISSUE THREAD

**Issue by nikicat** [Jesserc/gast#17]
Hello, I would like a subcommand that retrieves data sent by the `send-blob` subcommand from a tx.

**Comment by Jesserc** [comment]
Hi @nikicat https://github.com/Jesserc/gast/commit/56a0061cfb8294a8573ff99e8f0d973fb0c9d4ca adds a way to retrieve blob on mainnet, you can check the readme for an example

**Comment by nikicat** [comment]
Thank you, @Jesserc

**Comment by nikicat** [comment]
Could you suggest how to use it given that I have a blob transaction hash after sending the tx?
