### ISSUE TITLE
Migrate all supported RPC calls from ethclient to w3 - https://github.com/lmittmann/w3

### ISSUE THREAD

**Issue by Jesserc** [Jesserc/gast#5]

**Comment by krishnateja262** [comment]
Hi @Jesserc , can i take this up?

**Comment by Jesserc** [comment]
Yes

**Comment by krishnateja262** [comment]
#22 @Jesserc  this is a quick WIP PR, let me know if this aligns to what you are looking for. If its fine i can continue working on the remaining files

**Comment by Jesserc** [comment]
Thanks🙌
I will look into it tomorrow.
